import os

ENV_NAME = 'Breakout-v4'
ENV_NONSKIPPING_NAME = 'BreakoutNoFrameskip-v4'
ENV_SHORT_NAME = 'breakout'

# FOLDERS
PROJECT_ROOT_DIR = "./" + ENV_SHORT_NAME
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images")
POLICIES_PATH = os.path.join(PROJECT_ROOT_DIR, "policies/")
VIDEOS_PATH = os.path.join(PROJECT_ROOT_DIR, "videos")

# REPLAY BUFFER
REPLAY_BUFFER_MAX_LENGTH = 1000000
RANDOM_POLICY_PREFILL_STEPS = 20000

# TRAINING
UPDATE_PERIOD = 4 # run a training step every 4 collect steps
TRAINING_STEPS = 1000000
TRAINING_LOG_INTERVAL = 1000
TRAINING_SAVE_POLICY_INTERVAL = 100000
TRAINING_LOG_MEASURES_INTERVAL = 1000

# EVAL - VIDEO
NUM_VIDEO_EPISODES = 10
EVAL_POLICY_DIR='12232020-103407'


